import { curves } from "@kit.ArkUI";

export const NAV_PATH_STUCK = 'navPathStuck'
export const CONTEXT = 'context'
export const AVOID_AREA = 'AvoidAres';
export const animateParam: AnimateParam = { duration: 1500, curve: curves.springMotion(0.6, 0.7) };

export const WELCOME_WORD = [
  'HI，我是鸿小易，一名鸿蒙开发专家，有任何鸿蒙开发的问题都可以问我哦。',
  'Hello Wold，欢迎来到鸿蒙开发的世界，我是鸿蒙开发专家鸿小易，欢迎问我鸿蒙开发问题。',
  'Hi开发者！鸿小易在此待命，HarmonyOS应用开发中的疑难杂症，我们一起来攻克吧！',
  '欢迎进入鸿蒙世界！我是你的开发伙伴鸿小易，从环境配置到分布式开发，任何卡点都欢迎随时交流~',
  '你好呀~我是鸿小易，专注鸿蒙生态开发指导。无论是ArkUI还是Stage模型的问题，我都准备好为你解答啦！'
]
