import { curves } from "@kit.ArkUI";

export const NAV_PATH_STUCK = 'navPathStuck'

export const CONTEXT = 'context'

export const AVOID_AREA = 'AvoidAres';

export const animateParam: AnimateParam = { duration: 1500, curve: curves.springMotion(0.6, 0.7) };

export const WELCOME_WORD = [
  'HI，我是鸿小易，一名鸿蒙开发专家，有任何鸿蒙开发的问题都可以问我哦。',
  'Hello Wold，欢迎来到鸿蒙开发的世界，我是鸿蒙开发专家鸿小易，欢迎问我鸿蒙开发问题。',
  'Hi开发者！鸿小易在此待命，HarmonyOS应用开发中的疑难杂症，我们一起来攻克吧！',
  '欢迎进入鸿蒙世界！我是你的开发伙伴鸿小易，从环境配置到分布式开发，任何卡点都欢迎随时交流~',
  '你好呀~我是鸿小易，专注鸿蒙生态开发指导。无论是ArkUI还是Stage模型的问题，我都准备好为你解答啦！',
  '开发者你好！鸿小易已上线，HarmonyOS应用从工程创建到上架部署，全流程问题随时为你护航~',
  'Hi~这里是小易！无论是DevEco Studio使用技巧还是ArkTS语法难题，咱们鸿蒙开发者的问题没有冷场！',
  '欢迎加入鸿蒙开发者行列！遇到跨设备协同开发或原子化服务的实现难题？别犹豫，开始提问吧！',
  '你好开发者！我是鸿小易，专治HarmonyOS开发中的各种"疑难杂症"，API调用/性能优化/测试调试都OK！',
  '哈喽~鸿蒙生态开发者！从元服务开发到端云一体化，你的创新想法我来提供技术支撑！',
  '开发者你好！鸿小易已就位，无论是方舟编译器优化还是超级终端联调，让你的HarmonyOS应用性能起飞~',
  'Hi~鸿蒙极客！跨设备数据同步卡壳？FA模型与Stage模型选型纠结？别担心，咱们边聊边解！',
  '欢迎探索鸿蒙新特性！原子化服务卡片开发/一次开发多端部署难题，你的技术后援团已上线！',
  '开发者伙伴你好！从Ability调度到HAP包管理，HarmonyOS系统级开发问题随时call我！',
  '哈喽~鸿蒙安全守护者！想实现分布式数据安全或权限精准管控？小易的安全开发指南已备好！',
  'Hi Tech Leader！HarmonyOS跨端迁移方案/弹性部署实践，复杂场景开发我与你并肩作战！'
]
